# Generated by Django 5.1.6 on 2025-04-04 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_checkout_libraryuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='available_copies',
            new_name='copies_available',
        ),
    ]
